### ISSUE TITLE
Errors while trying ./experiments/scripts/sample_abstract.sh

### ISSUE THREAD

**Issue by ArwaTawfik** [uvavision/Text2Scene#10]
I am having errors while trying ./experiments/scripts/sample_abstract.sh
the message I get is the following:
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/sample_composites.txt.2021-04-12_17-41-19
+ exec
++ tee -a experiments/logs/sample_composites.txt.2021-04-12_17-41-19
tee: experiments/logs/sample_composites.txt.2021-04-12_17-41-19: No such file or directory
+ echo Logging output to experiments/logs/sample_composites.txt.2021-04-12_17-41-19
Logging output to experiments/logs/sample_composites.txt.2021-04-12_17-41-19
+ ./tools/abstract_demo.py --pretrained=abstract_final
Traceback (most recent call last):
  File "./tools/abstract_demo.py", line 35, in <module>
    abstract_demo(config)
  File "./tools/abstract_demo.py", line 18, in abstract_demo
    train_db = abstract_scene(config, split='val', transform=transformer)   
  File "/home/arwatawfik/Text2Scene/tools/../lib/datasets/abstract_scene.py", line 42, in __init__
    scenedb = self.load_scene(self.root_dir)
  File "/home/arwatawfik/Text2Scene/tools/../lib/datasets/abstract_scene.py", line 263, in load_scene
    fp = open(osp.join(db_dir, 'Scenes_10020.txt'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/arwatawfik/Text2Scene/tools/../lib/../data/AbstractScenes_v1.1/Scenes_10020.txt'

**Comment by fwtan** [comment]
Hi ArwaTawfik, it seems the program did not find the dataset. Have you downloaded the [AbstractScene](https://vision.ece.vt.edu/clipart/) dataset already? Or have you set the path to the dataset correctly?

**Comment by ArwaTawfik** [comment]
yes it worked, However it took a long time to download and install for bad internet connection.
could it work with more than the 300 words mentioned?
