### ISSUE TITLE
sample_composite.sh makes not result

### ISSUE THREAD

**Issue by Kelturon** [uvavision/Text2Scene#5]
After running sample_composite.sh i get the following:
dataset info loaded from /home/user/Text2Scene/data/caches/composites_coco_general.pkl
Loading color pallete.
Loading annotations into memory...
Done (t=13.99s)
creating index...
index created!
Loading annotations into memory...
Done (t=1.57s)
creating index...
index created!
Loading annotations into memory...
Done (t=31.39s)
creating index...
index created!
Killed

After all a new composite folder is created in the log directory but it contains no files
Please help, what could be causing the problem?

**Comment by Kelturon** [comment]
I found out that was a privilege issue.

But now ive started to get another error

index created!
wrote valdb to /home/videox/Text2Scene/data/caches/composites_coco_train.pkl
Filtered 3454 scenedb entries: 77783 -> 74329
Traceback (most recent call last):
  File "./tools/composites_demo.py", line 97, in <module>
    composites_demo(config)
  File "./tools/composites_demo.py", line 69, in composites_demo
    trainer = PuzzleTrainer(traindb)
  File "/home/videox/Text2Scene/tools/../lib/modules/puzzle_trainer.py", line 60, in __init__
    self.load_pretrained_net(self.cfg.pretrained)
  File "/home/videox/Text2Scene/tools/../lib/modules/puzzle_trainer.py", line 70, in load_pretrained_net
    assert osp.exists(pretrained_path)
AssertionError

**Comment by fwtan** [comment]
It seems the program didn't find the pretrained model. Have you downloaded the pretrained model and placed it in data/caches/composites_ckpts/ ?

**Comment by fwtan** [comment]
OK, I just noticed that the access permission of the server in our department is recently changed. I have regranted permission. You should be able to download the pretrained model by running "./experiments/scripts/fetch_models.sh"

**Comment by Kelturon** [comment]
thank you, im downloading at the moment. Will report on results later

**Comment by Kelturon** [comment]
Thank you so much for your help! Now I can see the pretrained model is downloaded but looks like there is still an issue
+ echo Logging output to experiments/logs/sample_composites.txt.2019-11-26_10-28-13
Logging output to experiments/logs/sample_composites.txt.2019-11-26_10-28-13
+ python3 ./tools/composites_demo.py --for_visualization=True --use_super_category=True --use_patch_background=True --n_shape_hidden=256 --where_attn=2 --where_attn_2d=True --pretrained=composites_final
dataset_info loaded from /home/videox/Text2Scene/data/caches/composites_coco_general.pkl
Loading color palette.
scenedb loaded from /home/videox/Text2Scene/data/caches/composites_coco_train.pkl
Filtered 3454 scenedb entries: 77783 -> 74329
Traceback (most recent call last):
  File "./tools/composites_demo.py", line 97, in <module>
    composites_demo(config)
  File "./tools/composites_demo.py", line 74, in composites_demo
    trainer.dump_shape_vectors(traindb)
  File "/home/videox/Text2Scene/tools/../lib/modules/puzzle_trainer.py", line 127, in dump_shape_vectors
    for cnt, batched in enumerate(loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/videox/Text2Scene/tools/../lib/datasets/composites_loader.py", line 140, in __getitem__
    entry['patch_vol'] = self.db.get_volume_from_indices(image_index, instance_ind)
  File "/home/videox/Text2Scene/tools/../lib/datasets/composites_coco.py", line 742, in get_volume_from_indices
    label = map(lambda x: self.class_ind_to_super_class_ind[x], label.flatten().tolist())
AttributeError: 'NoneType' object has no attribute 'flatten'

this is what Im getting after running sample_composite.sh

**Comment by fwtan** [comment]
Hi Keltron, have you followed the instruction and downloaded the data required?

**Comment by Kelturon** [comment]
yes, i followed all the instructions and succeded with the abstract scene and sample layout, than I did./experiments/scripts/fetch_models.sh" again after you regranted the permissions and still got the error above

**Comment by fwtan** [comment]
It seems the problem is caused by missing the required data, which can be downloaded by running `./experiments/scripts/fetch_aux.sh`. BTW, it is a huge zip file and it may take a while.

**Comment by Kelturon** [comment]
ok, ill try to delete the Text2Scene folder and restart downloading everything from scratch. Will report

**Comment by Kelturon** [comment]
looks like the aux_data.zip is not allowed to be downloaded from your server. I get 403 forbidden error

**Comment by fwtan** [comment]
Please check if you can download it now.

**Comment by Kelturon** [comment]
Ive rented a NY vps in purpose of working with this model. Now I can downoad aux_data.zip but fetch_models.sh outputs 403 forbidden

**Comment by fwtan** [comment]
Hi, I reset the access permission and test the links myself under different networks. I think you should be able to download them without using any vpn.

**Comment by Krist-steven** [comment]
I follow the instruction and download the required data,  but  I get the following error  after running sample_composite.sh

File
"/home/notebook/code/personal/multiModal/Text2Img/cocoapi/PythonAPI/Text2Scene/tools/../lib/nntable.py", line 60, in build_nntable
    with open(feature_path, 'rb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/notebook/code/personal/multiModal/Text2Img/cocoapi/PythonAPI/Text2Scene/tools/../lib/../data/coco/patch_feature_with_bg/train2017/000000303610/000000303610_000000422547.pkl'

**Comment by mogujiexuange** [comment]
> Hi, I reset the access permission and test the links myself under different networks. I think you should be able to download them without using any vpn.

Hi, I am very interest in your work;But It is too slow to download the 'aux_data.zip'; Would you send it to me using qq? My qq is 870438236; Thanks a lot!

**Comment by Kelturon** [comment]
I can report that everything is working fine now! Thanks a lot!
