### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by Krist-steven** [uvavision/Text2Scene#6]
I follow the instruction and download the required data,  but  I get the following error  after running sample_composite.sh

File
"/home/notebook/code/multiModal/Text2Img/cocoapi/PythonAPI/Text2Scene/tools/../lib/nntable.py", line 60, in build_nntable
    with open(feature_path, 'rb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/notebook/code/multiModal/Text2Img/cocoapi/PythonAPI/Text2Scene/tools/../lib/../data/coco/patch_feature_with_bg/train2017/000000303610/000000303610_000000422547.pkl'

I used try-except method to catch the exception, and found the following error:
person NNTable
File not found exception...
plant NNTable
File not found exception...

**Comment by fwtan** [comment]
Hi Krist-steven, can you remove the folders `data/coco/patch_feature_with_bg' and `caches/train_nntables_with_bg',  and rerun the demo.
In this case,  tools/composites_demo.py' will extract the per-patch feature again and rebuild the nntable, it may take a while though.

**Comment by Krist-steven** [comment]
Thank you for your reply,  the error has been solved.
