### ISSUE TITLE
lack of ram

### ISSUE THREAD

**Issue by partoCh** [uvavision/Text2Scene#9]
Hi, im running this code, but when i want to train the abstract scenes network on colab tpu i counter lack of memory, plz tell me if im doing wrong or the project wants more ram?(more than 12 G when traning )

**Comment by fwtan** [comment]
Could you provide more details about your experiment, e.g. OS system, training script, error message. 
12 GB in GPU should be enough, you could also try using a smaller batch size.

**Comment by partoCh** [comment]
i can see the demo of abstract scenes, but when i use the script for training, during running the process is killed/here is the error:


tcmalloc: large alloc 2635227136 bytes == 0x29b636000 @  0x7f8563106b6b 0x7f8563126379 0x7f84fbb5874e 0x7f84fbb5a7b6 0x7f8536cf399d 0x7f85463b68d0 0x7f8546034c1a 0x566bbc 0x50a433 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x508ec2 0x5a4c61 0x5a4fb8 0x4e012e 0x50a461 0x50beb4 0x507be4 0x588e5c 0x59fd0e 0x50d256 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x509900
/content/cocoapi/PythonAPI/Text2Scene/experiments/scripts/train_abstract.sh: line 10:  1436 Killed  

windows 7 ---> tpu of colab
!/content/cocoapi/PythonAPI/Text2Scene/experiments/scripts/train_abstract.sh

in code batch size is 8 , i changed it to numbers 1-6 but nothing special happened, and the same error is repeated!!!!/ i guess the problem happens some where before that line / or sth else is wrong

**Comment by partoCh** [comment]
i can see the demo of abstract scenes, but when i use the script for training, during running the process is killed/here is the error:

tcmalloc: large alloc 2635227136 bytes == 0x29b636000 @ 0x7f8563106b6b 0x7f8563126379 0x7f84fbb5874e 0x7f84fbb5a7b6 0x7f8536cf399d 0x7f85463b68d0 0x7f8546034c1a 0x566bbc 0x50a433 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x508ec2 0x5a4c61 0x5a4fb8 0x4e012e 0x50a461 0x50beb4 0x507be4 0x588e5c 0x59fd0e 0x50d256 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x509900
/content/cocoapi/PythonAPI/Text2Scene/experiments/scripts/train_abstract.sh: line 10: 1436 Killed

windows 7 ---> tpu of colab
!/content/cocoapi/PythonAPI/Text2Scene/experiments/scripts/train_abstract.sh

in code batch size is 8 , i changed it to numbers 1-6 but nothing special happened, and the same error is repeated!!!!/ i guess the problem happens some where before that line / or sth else is wrong

**Comment by fwtan** [comment]
Hi, the model is only tested on Linux and Nvidia GPU.
